name: RDS CLI Execution

on:
  push:
    branches:
      - main

jobs:
  execute-rds-script:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::347998599409:role/GitHubActions
          aws-region: us-east-1

      - name: Run Liquibase Migration
        uses: liquibase/liquibase-github-action@v4
        with:
          url: "jdbc:oracle:thin:@simplifynode.c5islbzvpxom.us-east-1.rds.amazonaws.com:1521/SFYNODE"
          username: "GALAXY_SHIELD_NAAP"
          password: "GALAXY_SHIELD_NAAP"
          changeLogFile: "db/changelog/db.changelog-master.yaml"
          operation: "update"
          classpath: "lib" 

