name: RDS CLI Execution

on:
  workflow_dispatch:  

jobs:
  execute-rds-script:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::347998599409:role/GitHubActions
          aws-region: us-east-1

      - name: Install Oracle Instant Client
        run: |
          sudo apt update && sudo apt install -y libaio-dev
          curl -L -o instantclient.zip "https://download.oracle.com/otn_software/linux/instantclient/instantclient-basiclite-linux.x64-21.10.0.0.0dbru.zip"
          unzip instantclient.zip -d /opt/oracle
          echo "/opt/oracle/instantclient_21_10" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=/opt/oracle/instantclient_21_10" >> $GITHUB_ENV
          echo "TNS_ADMIN=/opt/oracle/instantclient_21_10" >> $GITHUB_ENV


      - name: Test SQL Connection
        run: |
          echo "exit" | sql -S GALAXY_SHIELD_NAAP/GALAXY_SHIELD_NAAP@"jdbc:oracle:thin:@simplifynode.c5islbzvpxom.us-east-1.rds.amazonaws.com:1521/SFYNODE"

      - name: Run Liquibase Migration
        uses: liquibase/liquibase-github-action@v4
        with:
          operation: 'update'
          classpath: 'script/APPCATALOG'
          changeLogFile: 'samplechangelog.sql'
          url: "jdbc:oracle:thin:@simplifynode.c5islbzvpxom.us-east-1.rds.amazonaws.com:1521/SFYNODE"
          username: "GALAXY_SHIELD_NAAP"
          password: "GALAXY_SHIELD_NAAP"
