name: RDS CLI Execution

on:
  push:
    branches:
      - main

jobs:
  execute-rds-script:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::347998599409:role/GitHubActions
          aws-region: us-east-1

      - name: Execute SQL Script on RDS
        run: |
          aws rds execute-statement \
            --resource-arn arn:aws:rds:us-east-1:347998599409:db:simplifynode \
            --database simplifynode \
            --sql "SELECT NOW();"
