name: DB Execution

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Release Version"
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::347998599409:role/GitHubActionsEKSRole
          role-session-name: GitHubActionsEKSRole
          aws-region: us-east-1

      - name: Run DB Script
        run: |
          aws rds-data execute-statement \
            --resource-arn arn:aws:rds:us-east-1:347998599409:db:simplifynode \
            --database simplifynode \
            --sql "SELECT 1;"
