name: RDS CLI Execution

on:
  workflow_dispatch:  

jobs:
  execute-rds-script:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::347998599409:role/GitHubActions
          aws-region: us-east-1

      - name: Check RDS Instance Status
        run: |
          aws rds describe-db-instances --db-instance-identifier simplifynode --query "DBInstances[*].DBInstanceStatus"

      - name: Get Public IP
        id: ip
        run: echo "IP=$(curl -s ifconfig.me)" >> $GITHUB_ENV
        
      - name: Get RDS Security Group ID
        id: sg
        run: |
          RDS_INSTANCE_ID="simplifynode"
          SECURITY_GROUP_ID=$(aws rds describe-db-instances \
            --db-instance-identifier $RDS_INSTANCE_ID \
            --query "DBInstances[0].VpcSecurityGroups[0].VpcSecurityGroupId" \
            --output text)
          echo "SECURITY_GROUP_ID=$SECURITY_GROUP_ID" >> $GITHUB_ENV
          
      - name: Allow IP in Security Group
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ env.SECURITY_GROUP_ID }} \
            --protocol tcp --port 1521 --cidr ${{ env.IP }}/32

      - name: Test RDS Connection with Telnet
        run: |
          sudo apt-get update && sudo apt-get install -y telnet
          if telnet simplifynode.c5islbzvpxom.us-east-1.rds.amazonaws.com 1521; then
            echo "✅ Connection successful!"
          else
            echo "❌ Connection failed!"
            exit 1
          fi

      - name: Run Liquibase Migration
        uses: liquibase/liquibase-github-action@v4
        with:
          operation: 'update'
          classpath: 'script/APPCATALOG'
          changeLogFile: 'samplechangelog.sql'
          url: "jdbc:oracle:thin:@simplifynode.c5islbzvpxom.us-east-1.rds.amazonaws.com:1521/SFYNODE"
          username: "GALAXY_SHIELD_NAAP"
          password: "GALAXY_SHIELD_NAAP"
